cabal-version: 1.12

name:           cas-store
version:        1.1.1
synopsis:       A content-addressed storage
description:    A content-addressed storage supporting a remote caching. The API mainly consists of the cacheKleisliIO function which takes a (a -> m b) function and runs it only if the store doesn't already contain a result for it. Part of the funflow ecosystem.
category:       Control
homepage:       https://github.com/tweag/cas-store#readme
bug-reports:    https://github.com/tweag/cas-store/issues
author:         Tom Nielsen, Nicholas Clarke, Andreas Herrmann
maintainer:     Matthias Meschede <matthias.meschede@tweag.io>
license:        MIT
license-file:   LICENSE
build-type:     Simple
tested-with:    GHC==9.14.1, GHC==9.12.4, GHC==9.10.3, GHC==9.8.4, GHC==9.6.7
extra-source-files:
    changelog.md

source-repository head
  type: git
  location: https://github.com/tweag/cas-store
  subdir: cas-store

library
  exposed-modules:
      Data.CAS.ContentStore
      Data.CAS.Lock
      Data.CAS.RemoteCache
      Data.CAS.StoreOrphans
      Data.CAS.ContentStore.Notify
  hs-source-dirs:
      src
  ghc-options: -Wall
  build-depends:
      aeson >=2.1.0 && <2.3
    , async
    , base >=4.9 && <5
    , bytestring
    , cas-hashable
    , containers
    , cryptonite
    , directory
    , filepath
    , fsnotify
    , hashable >=1.4.1 && <1.6
    , hostname
    , lens >=5.2
    , path
    , path-io
    , random
    , safe-exceptions
    , sqlite-simple
    , store
    , tar
    , text >=2.0.1 && <2.2
    , unix
    , unliftio
  default-language: Haskell2010

test-suite unit-tests
  type: exitcode-stdio-1.0
  main-is: Test.hs
  other-modules:
      CAS.ContentStore
      Paths_cas_store
  hs-source-dirs:
      test
  ghc-options: -Wall -Wall -threaded
  build-depends:
      async
    , base
    , cas-hashable
    , cas-store
    , containers
    , path
    , path-io
    , safe-exceptions
    , tasty
    , tasty-hunit
    , unix
  default-language: Haskell2010
